server:
  port: ${PORT:8080}
  front-end-url: ${FRONT_END_URL:http://localhost:3000}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${APP_DB_URL:jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${APP_DB_USERNAME:root}
    password: ${APP_DB_PASSWORD:verysecret}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  flyway:
    locations: classpath:db.migration,classpath:dev.db.migration
    baseline-on-migrate: true
    baseline-version: 2
    enabled: true
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    sql-migration-separator: __
    repeatable-sql-migration-prefix: R
  data:
    redis:
      use-redis-cache: true
      host: ${APP_REDIS_HOST:localhost}
      port: ${APP_REDIS_PORT:6379}
    kafka:
      client:
        dns:
          lookup: use_dns_cache
      bootstrap-servers: ${APP_KAFKA_BROKER_SERVER:localhost}:${APP_KAFKA_BROKER_PORT:9092}
      producer:
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          "[spring.json.type.mapping]": category:com.ecommerce.shopapp.entity.Category
        consumer:
          value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
api:
  prefix: /api/v1
jwt:
  expiration: ${APP_JWT_EXPIRATION:2592000} #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: ${APP_JWT_EXPIRATION_REFRESH_TOKEN:5184000} #60 days = 60 * 24 * 60 * 60
  secretKey: ${APP_JWT_SECRET:secret}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /api/v1
mail:
  host: ${APP_MAIL_HOST:smtp.gmail.com}
  port: ${APP_MAIL_PORT:587}
  username: ${APP_MAIL_USERNAME:}
  password: ${APP_MAIL_PASSWORD:}
  smtpAuth: ${APP_MAIL_SMTP_AUTH:true}
  starttlsEnable: ${APP_MAIL_STARTTLS_ENABLE:true}
  smtpTLSEnable: ${APP_MAIL_SMTP_TLS_ENABLE:true}
  isSendToCC: ${APP_MAIL_IS_SEND_TO_CC:false}
  isSendToBCC: ${APP_MAIL_IS_SEND_TO_BCC:false}
